[package]
name = "computational_math"
version = "1.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "algr"
path = "./src/libs/alg/algr.rs"

[[bin]]
name = "lab1_task1"
path = "./src/lab1/task1/main.rs"